$(document).ready(function(){
  $(".blue").hover(function(event){
    event.preventDefault();
    $(".resultOfBlue").toggle();
    $(".blue").toggleClass("orange");
  });
  $(".purple").hover(function(event){
    event.preventDefault();
    $(".resultOfpurple").toggle();
    $(".purple").toggleClass("yellow");
  });
  $(".green").hover(function(event){
    event.preventDefault();
    $(".resultOfgreen").toggle();
    $(".green").toggleClass("blue");
  });
  $(".pinker").hover(function(event){
    event.preventDefault();
    $(".resultOfpinker").toggle();
    $(".pinker").toggleClass("orange");
  });
  $(".yellow").hover(function(event){
    event.preventDefault();
    $(".resultOfyellow").toggle();
    $(".yellow").toggleClass("green");
  });
  $(".white").hover(function(event){
    event.preventDefault();
    $(".resultOfwhite").toggle();
    $(".white").toggleClass("purple");
  });
  $(".red").hover(function(event){
    event.preventDefault();
    $(".resultOfred").toggle();
    $(".red").toggleClass("yellow");
  });
  $(".bluer").hover(function(event){
    event.preventDefault();
    $(".resultOfbluer").toggle();
    $(".bluer").toggleClass("pink");
  });
  $(".purplest").hover(function(event){
    event.preventDefault();
    $(".resultOfpurplest").toggle();
    $(".purplest").toggleClass("white");
  });
  $(".pink").hover(function(event){
    event.preventDefault();
    $(".resultOfpink").toggle();
    $(".pink").toggleClass("blue");
  });
  $(".orange").hover(function(event){
    event.preventDefault();
    $(".resultOforange").toggle();
    $(".orange").toggleClass("green");
  });
  $(".purpler").hover(function(event){
    event.preventDefault();
    $(".resultOfpurpler").toggle();
    $(".purpler").toggleClass("green");
  });
  $(".reder").hover(function(event){
    event.preventDefault();
    $(".resultOfreder").toggle();
    $(".reder").toggleClass("blue");
  });
  $(".yellower").hover(function(event){
    event.preventDefault();
    $(".resultOfyellower").toggle();
    $(".yellower").toggleClass("purple");
  });
  $(".whiter").hover(function(event){
    event.preventDefault();
    $(".resultOfwhiter").toggle();
    $(".whiter").toggleClass("white");
  });
  $(".greener").hover(function(event){
    event.preventDefault();
    $(".resultOfgreener").toggle();
    $(".greener").toggleClass("pink");
  });

});
